image: server-harbor:80/ant/ant_iit:devel

stages:
   - build
   - test
   - package
   - deploy

build:
  stage: build
  tags:
    - ant-devel
  script:
    - echo "Build stage started"
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    paths:
      - bin/*
      - build/*
    expire_in: 3 hrs

test:
  stage: test
  tags: 
    - ant-devel
  script:
    - echo "Test stage started"
    - cd build
    #- make -j$(nproc) main_tests
    #- ./tests/main_tests
    # TODO: go back to single main_test executable
    - ./tests/arm_unit_tests
    - ./tests/data_map_unit_tests
    - ./tests/dyn_params_unit_tests
    - ./tests/joint_unit_tests
    - ./tests/leg_unit_tests
    - ./tests/limb_unit_tests
    - ./tests/link_unit_tests
    - ./tests/robot_base_unit_tests
    - ./tests/trunk_unit_tests
    - ./tests/utils_unit_tests
  dependencies:
    - build

package:
  stage: package
  tags:
    - ant-devel
  script:
    - cd build
    - make package
    - echo $CI_JOB_ID > CI_JOB_ID   
  artifacts:
    paths:
      - build/*.deb
      - build/CI_JOB_ID
    expire_in: 3 hrs
  dependencies:
    - build
    - test

deploy:
  stage: deploy
  tags:
    - ant-devel
  script:
    - echo "Deploy stage started"
    - curl http://server-ubuntu18/scripts/make-json.bash --output make-json.bash
    - source make-json.bash token=$DLSUSER_TOKEN project=$CI_PROJECT_ID branch=$CI_COMMIT_BRANCH job=$(cat build/CI_JOB_ID) tag=latest release=$(lsb_release -cs) > out.json
    - 'curl -X post -H "Content-Type: application/json" -d @out.json http://server-ubuntu18:9000/hooks/deploy-apt'
  dependencies:
    - package