variables:
  REGISTRY: server-harbor:80

image: $REGISTRY/clones/ubuntu:20.04

stages:
  - build
  - test
  - package
  - deploy

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -y --no-install-recommends build-essential curl cmake libeigen3-dev libgtest-dev

build:
  stage: build
  tags:
    - dls
  script:
    - echo "Build stage started"
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc) install
    - cp /usr/lib/robots/* tests/
  artifacts:
    paths:
      - build/*
      - build/tests/*
    expire_in: 3 hrs

test:
  stage: test
  tags: 
    - dls
  script:
    - echo "Test stage started"
    - cd build/tests
    #- make -j$(nproc) main_tests
    #- ./tests/main_tests
    # TODO: go back to single main_test executable
    - ./arm_unit_tests
    - ./data_map_unit_tests
    - ./dyn_params_unit_tests
    - ./joint_unit_tests
    - ./leg_unit_tests
    - ./limb_unit_tests
    - ./link_unit_tests
    - ./robot_base_unit_tests
    - ./trunk_unit_tests
    - ./utils_unit_tests
  dependencies:
    - build

package:
  stage: package
  tags:
    - dls
  script:
    - cd build
    - make package
    - echo $CI_JOB_ID > CI_JOB_ID   
  artifacts:
    paths:
      - build/*.deb
      - build/CI_JOB_ID
    expire_in: 3 hrs
  dependencies:
    - build
    - test

deploy:
  stage: deploy
  tags:
    - dls
  script:
    - echo "Deploy stage started"
    - curl http://server-ubuntu18/scripts/make-json.bash --output make-json.bash
    - source make-json.bash token=$DLSUSER_TOKEN project=$CI_PROJECT_ID branch=$CI_COMMIT_BRANCH job=$(cat build/CI_JOB_ID) tag=latest release=$(lsb_release -cs) > out.json
    - 'curl -X post -H "Content-Type: application/json" -d @out.json http://server-ubuntu18:9000/hooks/deploy-apt'
  dependencies:
    - package